# In order to utilize this workflow, you must have OpenID Connect already set up in AWS.
# See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
# The following GitHub repository secrets must be present:
#     - GHA_ECR_ROLE_ASSUMPTION
#     - ECR_REPOSITORY

name: Automate Docker Build Push to AWS ECR

on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: false
        description: "The region where the ECR repo is located."
        default: "us-west-2"
    secrets:
      GHA_ECR_ROLE_ASSUMPTION:
        required: true
      ECR_REPOSITORY:
        required: true
permissions:
  id-token: write
  actions: read
  contents: read

jobs:
  build-and-push-dev-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # tag=v3.5.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5727f247b64f324ec403ac56ae05e220fd02b65f # v2
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ secrets.GHA_ECR_ROLE_ASSUMPTION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@2f9f10ea3fa2eed41ac443fee8bfbd059af2d0a4 # tag=v1.6.0

      - name: Construct image URI
        id: construct-image-uri
        env:
          GIT_BRANCH: ${{ github.ref_name }}
          GIT_COMMIT: ${{ github.sha }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: ${{ secrets.ECR_REPOSITORY }}
        shell: bash
        run: |
          BRANCH_PREFIX="$GIT_BRANCH"
          # use a generic prefix for all non-main branches
          if [[ "$BRANCH_PREFIX" != "main" ]]; then
            BRANCH_PREFIX="branch"
          fi
          BUILD_TIME=$(date '+%Y%m%d%H%M%S')
          IMAGE_TAG="${BRANCH_PREFIX}-${GIT_COMMIT}-${BUILD_TIME}"
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
          echo "image-uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2 # v2
        id: buildx
        with:
          install: true

      - name: Build and push
        uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf # v4
        with:
          context: .
          push: true
          tags: ${{ steps.construct-image-uri.outputs.image-uri }}
          build-args: |
            BUILD=${{ github.sha }}
          provenance: false
