name: Validate - Pre-Commit

on:
  workflow_call:
    inputs:
      python-version:
        description: "The Python version the workflow should run"
        default: "3.11"
        required: false
        type: string
      poetry-version:
        description: "The Poetry version the workflow should run"
        default: "1.4.2"
        required: false
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ inputs.python-version }}
      - uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4.0.0
        with:
          poetry-version: ${{ inputs.poetry-version }}
      - name: Install with Poetry
        run: poetry install
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ec # v3.0.1
      - name: Run Python tests
        run: poetry run pytest --full-trace
