name: validate

on:
  workflow_call:
    # workflows in the same organization or enterprise can use the inherit keyword to implicitly pass the secrets.

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: trussworks/circleci:56d41758666174506ef9a98769e448c63acc2045
      options: --user root
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-dot-cache-{{ hashFiles(.pre-commit-config.yaml') }}

      - name: Run pre-commit tests
        id: yarn-cache-dir-path
        run: pre-commit run --all-files --show-diff-on-failure
