name: Validate - Pre-Commit

on:
  workflow_call:
    inputs:
      python-version:
        description: "The Python version the workflow should run"
        default: "3.11"
        required: false
        type: string
      poetry-version:
        description: "The Poetry version the workflow should run"
        default: "1.4.2"
        required: false
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ inputs.poetry-version }}
      - name: Install with Poetry
        run: poetry install
      - uses: pre-commit/action@v3.0.1
      - name: Run Python tests
        run: poetry run pytest --full-trace
