name: Validate - Pre-Commit

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
      - uses: 8398a7/action-slack@v3
        if: ${{ failure() && github.actor == 'renovate' }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
