name: Validate - Terraform

on:
  workflow_call:
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

jobs:
  validate-tf:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load PAT secret
        id: load-pat-secret
        uses: 1password/load-secrets-action@v1
        env:
          PAT_SECRET: op://Infra/"Github - trussworks-infra"/credentials/validate-tf-token

      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.load-pat-secret.outputs.PAT_SECRET }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

      - uses: pre-commit/action@v3.0.0

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changes made by pre-commit
